import type { MenuCategory, MenuDish, TenantRestaurant } from './types'

export const DEMO_RESTAURANT: TenantRestaurant = {
  id: 'demo-restaurant',
  name: 'Restaurante IKON',
  description: 'Alta cocina mediterránea con vistas panorámicas al campo championship',
}

export const DEMO_MENU_CATEGORIES: MenuCategory[] = [
  { id: 'demo-cat-1', name: 'Entrantes', sort_order: 1 },
  { id: 'demo-cat-2', name: 'Principales', sort_order: 2 },
  { id: 'demo-cat-3', name: 'Postres', sort_order: 3 },
  { id: 'demo-cat-4', name: 'Bebidas', sort_order: 4 },
]

export const DEMO_MENU_DISHES: MenuDish[] = [
  {
    id: 'demo-d1',
    category_id: 'demo-cat-1',
    name: 'Gambas al ajillo',
    description: 'Gambas frescas en aceite de ajo y guindilla',
    price: 14.5,
    image_url: 'https://images.unsplash.com/photo-1565557623262-b51dbf251834?w=600&q=80',
    is_chef_special: true,
    is_vegetarian: false,
    is_vegan: false,
    is_gluten_free: true,
    is_available: true,
  },
  {
    id: 'demo-d2',
    category_id: 'demo-cat-1',
    name: 'Ensalada de burrata',
    description: 'Tomates heirloom, albahaca y aceite de oliva virgen',
    price: 12,
    image_url: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600&q=80',
    is_chef_special: false,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: true,
    is_available: true,
  },
  {
    id: 'demo-d3',
    category_id: 'demo-cat-2',
    name: 'Lubina a la brasa',
    description: 'Verduras de temporada y emulsión cítrica',
    price: 26,
    image_url: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&q=80',
    is_chef_special: false,
    is_vegetarian: false,
    is_vegan: false,
    is_gluten_free: true,
    is_available: true,
  },
  {
    id: 'demo-d4',
    category_id: 'demo-cat-2',
    name: 'Burger IKON',
    description: 'Wagyu, mayo de trufa y pan brioche',
    price: 22,
    image_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80',
    is_chef_special: false,
    is_vegetarian: false,
    is_vegan: false,
    is_gluten_free: false,
    is_available: true,
  },
  {
    id: 'demo-d5',
    category_id: 'demo-cat-3',
    name: 'Tiramisú',
    description: 'Receta clásica de la casa',
    price: 9,
    image_url: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&q=80',
    is_chef_special: false,
    is_vegetarian: true,
    is_vegan: false,
    is_gluten_free: false,
    is_available: true,
  },
  {
    id: 'demo-d6',
    category_id: 'demo-cat-4',
    name: 'Copa de vino de la casa',
    description: 'Tinto o blanco — bodega local',
    price: 6.5,
    image_url: 'https://images.unsplash.com/photo-1510812431400-5740424a8a0a?w=600&q=80',
    is_chef_special: false,
    is_vegetarian: true,
    is_vegan: true,
    is_gluten_free: true,
    is_available: true,
  },
]
